[env]
AG_IP = "127.0.0.1"
AG_PORT = "3000"
AG_HOST = "production"
AG_DATABASE_PORT = "5432"
AG_USERNAME = "access_grid"
AG_PASSWORD = "password"
AG_DATABASE = "access_grid"
AG_MAX_CONNECTIONS = "100"
AG_CONNECTION_TIMEOUT = "30"
